import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalNavbarLayout from "@/components/Gnb/global-layout";
import ModalProvider from "@/provider/modal-provider";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryProvider } from "@/provider/react-query-provider";
import SessionProvider from "@/provider/session-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <SessionProvider>
            <ModalProvider>
              <GlobalNavbarLayout>
                {children}
                <Toaster />
              </GlobalNavbarLayout>
            </ModalProvider>
          </SessionProvider>
        </ReactQueryProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
